print('Hello World')
print('My name is Kevin')
print('It is 1:32 am')
print('Tomorrow will be Sunday')
print('I love to hear the birds chirp')
print('My dog Benji likes to go on walks')
print('It is cold outside, I wish I had brought my coat')
